## Covariate data for PatchTST

This generates the data which can test whether PatchTST can detect covariate results. (21/04/2024)

In [1]:
import numpy as np
import pandas as pd

date_range = pd.date_range('2015-01-01', '2023-12-31', freq='H')
s1 = np.random.randn(len(date_range) + 24)
s2 = np.random.randn(len(date_range) +24)
s3 = s1 + s2

In [2]:

df = pd.DataFrame({'date': date_range, 's1': s1[24:], 's2': s2[24:], 'load': s3[:-24]})
df

                     date        s1        s2      load
0     2015-01-01 00:00:00 -1.310368 -1.994940 -0.408016
1     2015-01-01 01:00:00  0.428964 -1.005512 -0.763677
2     2015-01-01 02:00:00 -0.961720  0.417098 -2.291061
3     2015-01-01 03:00:00  0.356509  0.779911  0.309696
4     2015-01-01 04:00:00  0.251991 -0.379908  0.065318
...                   ...       ...       ...       ...
78860 2023-12-30 20:00:00 -0.139619  0.159873  0.750979
78861 2023-12-30 21:00:00  1.363466  3.124813 -0.131944
78862 2023-12-30 22:00:00 -1.381556  1.403176 -2.858786
78863 2023-12-30 23:00:00  0.636198 -0.079560 -1.684969
78864 2023-12-31 00:00:00 -0.037350  0.700268 -0.730948

[78865 rows x 4 columns]

In [3]:
df.to_csv('./../../data/preproc/covariatess.csv', index=False)