## Covariate data for PatchTST

This generates the data which can test whether PatchTST can detect covariate results. (21/04/2024)

In [1]:
import numpy as np
import pandas as pd

date_range = pd.date_range('2015-01-01', '2023-12-31', freq='H')
s1 = np.random.randn(len(date_range) + 24)
s2 = np.random.randn(len(date_range) +24)
s3 = s1 + s2

In [2]:

df = pd.DataFrame({'date': date_range, 's1': s1[24:], 's2': s2[24:], 'load': s3[:-24]})
df

                     date        s1        s2      load
0     2015-01-01 00:00:00  1.085003 -0.740027 -0.811802
1     2015-01-01 01:00:00  0.673705 -0.401645 -1.216270
2     2015-01-01 02:00:00 -0.250837  0.956364 -2.065147
3     2015-01-01 03:00:00 -1.278848 -0.653833 -0.372431
4     2015-01-01 04:00:00 -1.540048  0.751464  3.035381
...                   ...       ...       ...       ...
78860 2023-12-30 20:00:00  2.269739 -0.142944 -1.913709
78861 2023-12-30 21:00:00  0.941170  1.535137  2.470601
78862 2023-12-30 22:00:00  0.870745 -0.801395  0.613285
78863 2023-12-30 23:00:00  0.682681 -1.932939  1.141645
78864 2023-12-31 00:00:00 -0.122176  1.008811  0.116122

[78865 rows x 4 columns]

In [3]:
df.to_csv('./../../data/preproc/covariate.csv', index=False)